/** Bundled item reference database (generated by tools/extract-items.mjs). */
import raw from '../../core/data/items.json';

export interface ItemRef {
  id: string;
  name: string;
  type: 'O' | 'BC' | 'W' | 'F' | 'B' | 'H' | 'S' | 'P' | 'T';
  category: number;
  price?: number;
  edibility?: number;
  sprite?: number;
}

export const TYPE_LABELS: Record<ItemRef['type'], string> = {
  O: 'Object',
  BC: 'Big craftable',
  W: 'Weapon',
  F: 'Furniture',
  B: 'Boots',
  H: 'Hat',
  S: 'Shirt',
  P: 'Pants',
  T: 'Tool',
};

const db = raw as { items: ItemRef[] };

export const ITEMS: ItemRef[] = db.items;

/** Only plain Objects can be added from the picker in v1 (full-fidelity template). */
export const ADDABLE_ITEMS: ItemRef[] = ITEMS.filter((i) => i.type === 'O');

export function searchItems(query: string, pool: ItemRef[] = ADDABLE_ITEMS, limit = 40): ItemRef[] {
  const q = query.trim().toLowerCase();
  if (!q) return pool.slice(0, limit);
  const starts: ItemRef[] = [];
  const contains: ItemRef[] = [];
  for (const item of pool) {
    const name = item.name.toLowerCase();
    if (name.startsWith(q)) starts.push(item);
    else if (name.includes(q) || item.id.toLowerCase() === q) contains.push(item);
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}
